### ISSUE TITLE
Long name problem

### ISSUE THREAD

**Issue by cyrinux** [guillaumev/piwigoshotwell#1]
Hi,

I have some problem when i publish file with long name.
But this work with pLoader from piwigo.
I'm running Ubuntu 10.10 on french system and the lastest piwigo 2.1.6

Thanks for your help

I have post also here http://piwigo.org/forum/viewtopic.php?id=16667
"
Hi,

I can see picture sent by shotwell when they are long name.

It is possible to include rename/correct file name before uploading ?

example : 27-06-2009 à 03-41-30_IMG_0557 7857.jpg

on piwigo i see it try to open     20110210135136-.jpg

But if i send other picture, with a shortest name, this works.

Thanks for your help
"

**Comment by guillaumev** [comment]
Hi Cyril,

Thanks for the bug report. Unfortunately, I'm very busy on other projects currently, so I don't have time to fix it right away, but I'll try to do so in the future...

Best regards.

**Comment by cyrinux** [comment]
Hi,

Ok thanks for read me, I hope you will find time quickly ^^

Thanks for your work

Best regards.
